name: CI Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: sqlite:///mlflow.db
      MLFLOW_ALLOW_FILE_STORE: true


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install Dependency
      run: |
        pip install --upgrade pip
        pip install mlflow==2.19.0
        pip install -r MLProject/requirements.txt


    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run .